//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCLaborClient.LaborService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LaborService.ILaborService")]
    public interface ILaborService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILaborService/GetMessage", ReplyAction="http://tempuri.org/ILaborService/GetMessageResponse")]
        string GetMessage();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ILaborServiceChannel : MCLaborClient.LaborService.ILaborService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class LaborServiceClient : System.ServiceModel.ClientBase<MCLaborClient.LaborService.ILaborService>, MCLaborClient.LaborService.ILaborService {
        
        public LaborServiceClient() {
        }
        
        public LaborServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LaborServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LaborServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LaborServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMessage() {
            return base.Channel.GetMessage();
        }
    }
}
